-- 15. Create table transactions
CREATE TABLE transactions (
  id UUID NOT NULL,
  isIncome BOOLEAN NOT NULL,
  projectId UUID NOT NULL,
  amount DECIMAL(11,2) NOT NULL,
  currencyId UUID NOT NULL,
  tradingDate DATE NOT NULL,
  amountNOK DECIMAL(11,2) NOT NULL,
  fromMemberId UUID NULL,
  toBeneficiaryId UUID NULL,
  typeId UUID NOT NULL,
  description VARCHAR(192) NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_PROJECT_ID FOREIGN KEY (projectId) REFERENCES projects (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_CURRENCY_ID FOREIGN KEY (currencyId) REFERENCES currency (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_MEMBER_ID FOREIGN KEY (fromMemberId) REFERENCES members (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_BENEFICIARY_ID FOREIGN KEY (toBeneficiaryId) REFERENCES beneficiaries (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_TYPE_ID FOREIGN KEY (typeId) REFERENCES transaction_types (id) ON DELETE NO ACTION ON UPDATE NO ACTION
)
;