package ua.petros.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;
import ua.petros.model.*;
import ua.petros.service.*;

import java.util.Comparator;
import java.util.List;

/**
 * A Spring controller that allows the users to download an Excel document
 * generated by the Apache POI library.
 * 
 * @author www.codejava.net
 * 
 */
@Controller
public class ExcelFileDownloadController {

	@Autowired
	private UserService userService;

	@Autowired
	private MemberService memberService;

	@Autowired
	private BeneficiaryService beneficiaryService;

	@Autowired
	private ProjectService projectService;

	@Autowired
	private ProjectMemberService projectMemberService;

	@Autowired
	private TransactionService transactionService;

	/**
	 * Handle request to download an Excel document 
	 */
	@RequestMapping(value = "/reports/users/excel", method = RequestMethod.GET)
	public ModelAndView downloadExcelUsers() {

		List<User> listUsers = userService.getAll();

		// return a view which will be resolved by an excel view resolver
		return new ModelAndView("excelUsersView", "listUsers", listUsers);
	}

	@RequestMapping(value = "/reports/members/excel", method = RequestMethod.GET)
	public ModelAndView downloadExcelMembers() {

		List<Member> listMembers = memberService.getAll();

		// return a view which will be resolved by an excel view resolver
		return new ModelAndView("excelMembersView", "listMembers", listMembers);
	}

	@RequestMapping(value = "/reports/beneficiaries/excel", method = RequestMethod.GET)
	public ModelAndView downloadExcelBeneficiaries() {

		List<Beneficiary> listBeneficiaries = beneficiaryService.getAll();

		// return a view which will be resolved by an excel view resolver
		return new ModelAndView("excelBeneficiariesView", "listBeneficiaries", listBeneficiaries);
	}

	@RequestMapping(value = "/reports/projects/excel", method = RequestMethod.GET)
	public ModelAndView downloadExcelProjects() {

		List<Project> listProjects = projectService.getAll();

		// return a view which will be resolved by an excel view resolver
		return new ModelAndView("excelProjectsView", "listProjects", listProjects);
	}

	@RequestMapping(value = "/reports/project/members/excel", method = RequestMethod.GET)
	public ModelAndView downloadExcelProjectMembers() {

		List<ProjectMember> listProjectMembers = projectMemberService.getAll();
		listProjectMembers.sort(Comparator.naturalOrder());

		// return a view which will be resolved by an excel view resolver
		return new ModelAndView("excelProjectMembersView", "listProjectMembers", listProjectMembers);
	}

	@RequestMapping(value = "/reports/transactions/excel", method = RequestMethod.GET)
	public ModelAndView downloadExcelTransactions() {

		List<Transaction> listTransactions = transactionService.getAll();
		listTransactions.sort(Comparator.naturalOrder());

		// return a view which will be resolved by an excel view resolver
		return new ModelAndView("excelTransactionsView", "listTransactions", listTransactions);
	}
}