package ua.petros.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;
import ua.petros.model.*;
import ua.petros.service.*;

import java.util.List;
import java.util.stream.Collectors;

/**
 * A Spring controller that allows the users to download a PDF document
 * generated by the Apache POI library.
 * 
 * @author www.codejava.net
 * 
 */
@Controller
public class PDFFileDownloadController {

	@Autowired
	private UserService userService;

	@Autowired
	private MemberService memberService;

	@Autowired
	private BeneficiaryService beneficiaryService;

	@Autowired
	private ProjectService projectService;

	@Autowired
	private ProjectMemberService projectMemberService;

	@Autowired
	private TransactionService transactionService;

	/**
	 * Handle request to download PDF document
	 */

	@RequestMapping(value = "/reports/projects/pdf", method = RequestMethod.GET)
	public ModelAndView downloadPDFProjects() {

		List<Project> listProjects = projectService.getAll();
		List<Project> sortedListProjects = listProjects.stream().sorted().collect(Collectors.toList());

		// return a view which will be resolved by a pdf view resolver
		return new ModelAndView("pdfProjectsView", "listProjects", sortedListProjects);
	}
}